### ISSUE TITLE
我有一个部署上面的问题

### ISSUE THREAD

**Issue by Team-boy** [perfree/go-fastdfs-web#34]
[root@node02 go-fastdfs-web]# java -jar go-fastdfs-web.jar 
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/usr/go-fastdfs-web/go-fastdfs-web.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/usr/go-fastdfs-web/go-fastdfs-web.jar!/BOOT-INF/lib/slf4j-log4j12-1.7.25.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.1.3.RELEASE)

2020-07-25 16:25:17.378  INFO 2202 --- [           main] com.perfree.Application                  : Starting Application v1.0.0 with PID 2202 (/usr/go-fastdfs-web/go-fastdfs-web.jar started by root in /usr/go-fastdfs-web)
2020-07-25 16:25:17.380  INFO 2202 --- [           main] com.perfree.Application                  : The following profiles are active: prod
2020-07-25 16:25:19.062  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'shiroConfig' of type [com.perfree.config.ShiroConfig$$EnhancerBySpringCGLIB$$83abc3be] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.082  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$7fb748e0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.712  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'mybatis-org.mybatis.spring.boot.autoconfigure.MybatisProperties' of type [org.mybatis.spring.boot.autoconfigure.MybatisProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.744  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration' of type [org.mybatis.spring.boot.autoconfigure.MybatisAutoConfiguration$$EnhancerBySpringCGLIB$$b28b9a10] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.756  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'SQLiteConfiguration' of type [com.perfree.config.SQLiteConfiguration$$EnhancerBySpringCGLIB$$8ce2955] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.765  INFO 2202 --- [           main] com.perfree.config.SQLiteConfiguration   : sqlite path地址 = /db/go-fastdfs.db
2020-07-25 16:25:19.771  INFO 2202 --- [           main] com.perfree.config.SQLiteConfiguration   : 最终配置的值spring.datasource.url = jdbc:sqlite:/usr/go-fastdfs-web/db/go-fastdfs.db
2020-07-25 16:25:19.811  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'dataSource' of type [com.zaxxer.hikari.HikariDataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.837  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'spring.datasource-org.springframework.boot.autoconfigure.jdbc.DataSourceProperties' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceProperties] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.854  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker' of type [org.springframework.boot.autoconfigure.jdbc.DataSourceInitializerInvoker] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:19.988  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sqlSessionFactory' of type [org.apache.ibatis.session.defaults.DefaultSqlSessionFactory] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.004  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sqlSessionTemplate' of type [org.mybatis.spring.SqlSessionTemplate] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.124  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'userMapper' of type [org.mybatis.spring.mapper.MapperFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.133  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'userMapper' of type [com.sun.proxy.$Proxy55] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.140  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'userService' of type [com.perfree.service.UserService] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.169  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'peersMapper' of type [org.mybatis.spring.mapper.MapperFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.169  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'peersMapper' of type [com.sun.proxy.$Proxy60] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.171  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'customRealm' of type [com.perfree.config.ShiroRealm] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.183  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'sessionManager' of type [org.apache.shiro.web.session.mgt.DefaultWebSessionManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.187  INFO 2202 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'securityManager' of type [org.apache.shiro.web.mgt.DefaultWebSecurityManager] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-07-25 16:25:20.770  INFO 2202 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8088 (http)
2020-07-25 16:25:20.830  INFO 2202 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2020-07-25 16:25:20.830  INFO 2202 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.16]
2020-07-25 16:25:20.850  INFO 2202 --- [           main] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/usr/java/packages/lib/amd64:/usr/lib64:/lib64:/lib:/usr/lib]
2020-07-25 16:25:20.980  INFO 2202 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2020-07-25 16:25:20.980  INFO 2202 --- [           main] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 3538 ms
2020-07-25 16:25:21.561  INFO 2202 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2020-07-25 16:25:21.862  INFO 2202 --- [           main] o.s.b.a.w.s.WelcomePageHandlerMapping    : Adding welcome page template: index
2020-07-25 16:25:22.164  INFO 2202 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8088 (http) with context path ''
2020-07-25 16:25:22.170  INFO 2202 --- [           main] com.perfree.Application                  : Started Application in 11.015 seconds (JVM running for 11.626)
2020-07-25 16:25:27.368  INFO 2202 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-07-25 16:25:27.373 ERROR 2202 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:816) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:797) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:324) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at com.perfree.Application.main(Application.java:23) [classes!/:1.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_141]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_141]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_141]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_141]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [go-fastdfs-web.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [go-fastdfs-web.jar:1.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [go-fastdfs-web.jar:1.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [go-fastdfs-web.jar:1.0.0]
Caused by: java.net.UnknownHostException: node02: node02: Name or service not known
	at java.net.InetAddress.getLocalHost(InetAddress.java:1505) ~[na:1.8.0_141]
	at com.perfree.Application.run(Application.java:28) [classes!/:1.0.0]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:813) [spring-boot-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	... 13 common frames omitted
Caused by: java.net.UnknownHostException: node02: Name or service not known
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:1.8.0_141]
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928) ~[na:1.8.0_141]
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323) ~[na:1.8.0_141]
	at java.net.InetAddress.getLocalHost(InetAddress.java:1500) ~[na:1.8.0_141]
	... 15 common frames omitted

2020-07-25 16:25:27.387  INFO 2202 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'applicationTaskExecutor'
[root@node02 go-fastdfs-web]#

**Comment by perfree** [comment]
已修改,感谢反馈
